#!/usr/bin/bash
#LOBSTER_ROOT=/home/thawasta/codespace/Lobster-MVC-Rebuild
cd $LOBSTER_ROOT
sudo git config --global --add safe.directory $LOBSTER_ROOT
sudo git commit -a -m "Commit from Pi"
sudo get reset --hard
sudo git pull
sudo npm install
node ./index.js