#!/usr/bin/bash
#LOBSTER_ROOT=/home/thawasta/codespace/Lobster-MVC-Rebuild
cd $LOBSTER_ROOT
git config --global --add safe.directory $LOBSTER_ROOT
git config pull.ff only
echo "Attempting commit"
git commit -a -m "Commit from Pi"
echo "git reset"
git reset --hard
echo "git stash"
git stash
echo "drop stash"
git stash drop
echo "git pull"
git pull
npm install
node ./index.js